//! Calibrate command implementation.

use colored::Colorize;

/// Run the calibrate command.
///
/// # Errors
///
/// Returns an error if calibration fails.
pub fn run(data_path: String, output: String) -> Result<(), Box<dyn std::error::Error>> {
    println!("{} Calibrating QJL quantizer...", "⚙".cyan().bold());
    println!("  Data: {}", data_path.cyan());
    println!("  Output: {}", output.cyan());

    // Generate calibration params
    use turboquant_core::qjl::{CorrectionMode, QjlConfig, QjlQuantizer, ScaleMode};

    let config = QjlConfig {
        bits: 3,
        block_size: 64,
        scale_mode: ScaleMode::Adaptive,
        correction: CorrectionMode::OneBitResidual {
            learned_scale: 0.01,
        },
    };

    let quantizer = QjlQuantizer::new(config);
    let config = quantizer.config();

    // Write calibration YAML
    let yaml = format!(
        r"# TurboQuant Calibration Parameters
# Generated by: turboquant calibrate
bits: {}
block_size: {}
scale_mode: Adaptive
correction:
  type: OneBitResidual
  learned_scale: 0.01
",
        config.bits, config.block_size
    );

    std::fs::write(&output, yaml)?;
    println!(
        "{} Calibration saved to {}",
        "✓".green().bold(),
        output.cyan()
    );

    Ok(())
}
